# Generated by Django 2.0.2 on 2018-06-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethereum',
            options={'ordering': ['id']},
        ),
    ]
